services:
  bmstu-direct-bot:
    container_name: bmstu-direct-bot
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - "8000:8000"
    networks:
      - host
    depends_on:
      - bmstu-direct-db

  bmstu-direct-db:
    image: postgres:16.3-alpine3.20
    container_name: bmstu-direct-db
    environment:
      - POSTGRES_DB=${db_name}
      - POSTGRES_USER=${db_user}
      - POSTGRES_PASSWORD=${db_password}
    ports:
      - "54321:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ${db_name}" ]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 10s
    networks:
      - host

networks:
  host:
    driver: bridge
