services:
  bmstu-direct-bot:
    container_name: bmstu-direct-bot
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    networks:
      - host
    depends_on:
      - bmstu-direct-db

  bmstu-direct-db:
    image: postgres:16.3-alpine3.20
    container_name: bmstu-direct-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "54321:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 10s
    networks:
      - host

networks:
  host:
    driver: bridge
