name: Bots CI

on:
  push

jobs:
  deploy:
    name: "Deploy bots service"
    runs-on: "ubuntu-latest"
    environment: production
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd ${{ vars.PROJECT_DIR }}
            docker compose --env-file=.env down
            git stash
            git checkout main
            git pull origin main
            docker compose --env-file=.env up --build -d
